In [1]:
import numpy as numpy
import pandas as pd

Creating a dataFrame

In [5]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df = pd.DataFrame(data)

In [6]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [10]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
columns = ['name' ,'age', 'city' ,'salary']
df2=pd.DataFrame(data_list , columns=columns)
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

selection and indexing of columns

In [29]:
df2[["name","city"]]  #single , double quotes kuch bhi use kr skte ho

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

In [30]:
df2['designation'] = ['engin' , 'doct' , 'engin' , 'doct']

In [31]:
df2

    name  age      city  salary designation
0   John   28  New York   65000       engin
1   Anna   34     Paris   70000        doct
2  Peter   29    Berlin   62000       engin
3  Linda   42    London   85000        doct

In [32]:
df2.drop('designation' , axis =1 , inplace = True)

In [33]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [35]:
df2.drop(["name" ,"city"] , axis =1)

   age  salary
0   28   65000
1   34   70000
2   29   62000
3   42   85000

In [36]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [37]:
df2.drop(0) #axis de skte ho but by default 0 hi hota h

    name  age    city  salary
1   Anna   34   Paris   70000
2  Peter   29  Berlin   62000
3  Linda   42  London   85000

In [38]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [46]:
df2.loc[0]

name          John
age             28
city      New York
salary       65000
Name: 0, dtype: object

In [47]:
df2.loc[[0,1]]

   name  age      city  salary
0  John   28  New York   65000
1  Anna   34     Paris   70000

In [48]:
df2.iloc[3] #index locatiom

name       Linda
age           42
city      London
salary     85000
Name: 3, dtype: object

Selecting subsets of rows and columns

In [50]:
df2.loc[[0,1]] [['city','salary']]

       city  salary
0  New York   65000
1     Paris   70000

In [52]:
df2.loc[[2,3]] [['name' , 'age']]

    name  age
2  Peter   29
3  Linda   42

In [55]:
df2[df2['age'] > 30]

    name  age    city  salary
1   Anna   34   Paris   70000
3  Linda   42  London   85000

In [61]:
df2[(df2['age'] > 30) & (df2['city']=='Paris')]

   name  age   city  salary
1  Anna   34  Paris   70000