In [14]:
import numpy as np
import pandas as pd

In [15]:
data= { 
    'date' : pd.date_range('2023-12-1' , periods=8)
}
pd.DataFrame(data)

        date
0 2023-12-01
1 2023-12-02
2 2023-12-03
3 2023-12-04
4 2023-12-05
5 2023-12-06
6 2023-12-07
7 2023-12-08

In [16]:
df = pd.DataFrame(data)
df.index = range(1, len(df) + 1)

In [17]:
df

        date
1 2023-12-01
2 2023-12-02
3 2023-12-03
4 2023-12-04
5 2023-12-05
6 2023-12-06
7 2023-12-07
8 2023-12-08

In [18]:
data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [19]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [20]:
# Group by Category and calculate the sum of Sales


cat=df.groupby('Category')
cat #ye object bn jaega   jisko aap deh nhi paoge
for i , v in cat:   
    print(i) #upar left corner pr A and B alag se print hue h dekho
    print(v)

    # Basically groupby() ne jitni bhi unique categories thi (A, B, C), unke alag-alag DataFrames bana diye. Phir for i, v in cat me har iteration par i me group ka naam aaya (A, B, C) aur v me us group ka DataFrame aaya. Isliye print(i) group ka naam print karta hai aur print(v) us group ki saari rows print karta hai.

A
  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
2        A    S2    150        12 2023-01-03
4        A    S1    120         8 2023-01-05
6        A    S2    200        15 2023-01-07
B
  Category Store  Sales  Quantity       Date
1        B    S1    200        15 2023-01-02
3        B    S2    250        18 2023-01-04
5        B    S2    180        20 2023-01-06
7        B    S1    300        25 2023-01-08

In [21]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [22]:
cat = df.groupby('Category')['Sales'].sum()  #sales ko select krke sum print kr diya
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [23]:
# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [24]:
# group by categorical pr hota h which is qualitative data like A and B , and other is quantitative data

In [25]:
# Group by multiple columns
# Group by Category and Storeabs

cat=df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

In [26]:
# Aggregation ka mtlb hota h multiple cheejo ko combine krke answer nikalna  , basic agg. hote h mean , mode , median , SD , variance

Aggregation

In [29]:
print(df['Sales'].mean())
# mean median min max count std

187.5

In [30]:
df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64