In [9]:
import numpy as np
import pandas as pd

In [19]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [20]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [21]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [22]:
df.isna().sum() #har row mw kitni null values h bta dega

A    1
B    0
C    2
D    3
dtype: int64

In [23]:
df.isna().any() #ye btaega har column me ek null value hai ya nhi

A     True
B    False
C     True
D     True
dtype: bool

Removing the missing data

In [24]:
#remove hamesha row wise krte h jsi row me null value hogi vo reove ho jaegi
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [27]:
# thresh me jo value dege us hisab se check krega jsi row me utni null value hogi unko remove nhi krega else ko remove kr dega 
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [28]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

filling the mising data

In [29]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [31]:
df.fillna(300) #jaha jaha null thwa vha 300 fill ho gya
#fill column wise hota h , selection fill row wise hota h

       A  B      C      D
0    1.0  1    1.0    1.0
1    2.0  2    2.0  300.0
2  300.0  3    3.0  300.0
3    4.0  4  300.0  300.0
4    5.0  5  300.0    5.0

In [32]:
values = {'A':23 , 'B':24 , 'C':35,'D':26}
df.fillna(value=values)

      A  B     C     D
0   1.0  1   1.0   1.0
1   2.0  2   2.0  26.0
2  23.0  3   3.0  26.0
3   4.0  4  35.0  26.0
4   5.0  5  35.0   5.0

In [33]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0